SEQUENCE: '002_ballroom'
# INVALID_ARIAS: ['aria02']
INVALID_ARIAS: []

INVALID_EXOS: []

CALIBRATION:
  MANUAL_EXO_CAMERAS: []

BBOX:
  MIN_VERTICES: 40
  ROI_CYLINDER_RADIUS: 0.5
  HUMAN_HEIGHT: 1.4
  EGO:
    MIN_AREA_RATIO: 0.001
    CLOSE_BBOX_DISTANCE: 2.0
    CLOSE_BBOX_MIN_AREA_RATIO: 0.01
    MAX_ASPECT_RATIO: 4
    MIN_ASPECT_RATIO: 0.4

  EXO:
    MIN_AREA_RATIO: 0.0005
    MAX_ASPECT_RATIO: 5
    MIN_ASPECT_RATIO: 0.5
  
  SAVE_OFFSHELF_BOX_TO_DISK: False

POSE2D:
  DEBUG: False
  # USE_BBOX_DETECTOR: False
  USE_BBOX_DETECTOR: True
  DETECTOR_CONFIG_FILE: '/home/rawalk/Desktop/ego/mmpose/demo/mmdetection_cfg/faster_rcnn_x101_64x4d_fpn_mstrain_3x_coco.py'
  DETECTOR_CHECKPOINT: 'https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_x101_64x4d_fpn_mstrain_3x_coco/faster_rcnn_x101_64x4d_fpn_mstrain_3x_coco_20210524_124528-26c63de6.pth'
  DETECTOR_MIN_IOU: 0.1

  # RGB_CONFIG_FILE: '/home/rawalk/Desktop/ego/mmpose/configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/hrnet_w48_coco_wholebody_384x288_dark_plus.py'
  # RGB_CHECKPOINT: 'https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth'
  
  # ## vitpose for rgb  
  RGB_CONFIG_FILE: '/home/rawalk/Desktop/ego/vitpose/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/ViTPose_huge_coco_256x192.py'
  RGB_CHECKPOINT: '/media/rawalk/disk1/rawalk/vitpose/checkpoints/vitpose-h-multi-coco.pth'

  # ## segmentation conditioned vitpose for rgb
  # RGB_SEG_CONFIG_FILE: '/home/rawalk/Desktop/ego/vitpose/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/seg_ViTPose_base_coco_256x192.py'
  # RGB_SEG_CHECKPOINT: '/media/rawalk/disk1/rawalk/vitpose/seg_checkpoints/base_epoch_210.pth'
  ## segmentation conditioned vitpose for rgb
  RGB_SEG_CONFIG_FILE: '/home/rawalk/Desktop/ego/vitpose/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/seg_ViTPose_large_coco_256x192.py'
  RGB_SEG_CHECKPOINT: '/media/rawalk/disk1/rawalk/vitpose/seg_checkpoints/large_epoch_140.pth'

  RGB_THRES: 0.2
  RGB_VIS_THRES: 0.2
  
  GRAY_CONFIG_FILE: '/home/rawalk/Desktop/ego/mmpose/configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody-grayscale/hrnet_w48_coco_wholebody_384x288_dark_plus.py'
  GRAY_CHECKPOINT: 'https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth'

  GRAY_THRES: 0.5
  GRAY_VIS_THRES: 0.5

  MIN_VIS_KEYPOINTS: 5
  # OVERLAP_OKS_THRES: 0.7 ## very important, default, if overlap greater than this remove
  OVERLAP_OKS_THRES: 0.6

  BBOX_THRES: 0.5

  VIS:
    RADIUS:
      EXO_RGB: 10
      EGO_RGB: 5
      EGO_LEFT: 2
      EGO_RIGHT: 2
    THICKNESS:
      EXO_RGB: 10
      EGO_RGB: 5
      EGO_LEFT: 2
      EGO_RIGHT: 2

POSE3D:
  # VIS_CAMERAS: ['cam08', 'cam11', 'cam14']
  VIS_CAMERAS: []
  KEYPOINTS_THRES: 0.5
  BBOX_AREA_THRES: 0.002
  NUM_ITERS: 500
  REPROJECTION_ERROR_EPSILON: 0.01
  USE_SEGPOSE2D: False

  MIN_VIEWS: 2 ## min views for triangulation
  SECONDARY_MIN_VIEWS: 3 ## min views for triangulation
  INCLUDE_CONFIDENCE: True ## include confidence in triangulation  

REFINE_POSE3D:
  DEBUG: True
  STD_THRES: 10 ##+- std deviation allowed for inliers
  WINDOW_LENGTH: 10
  MOTION_THRES: 300 ## in pixels 4k

FIT_POSE3D:
  DEBUG: True
  NUM_EPOCHS: 10
  NUM_ITERS: 500
  LR: 0.1
  MAX_ITER: 20
  INIT_POSE_LOSS_WEIGHT: 1
  SYMMETRY_LOSS_WEIGHT: 1
  TEMPORAL_LOSS_WEIGHT: 1
  LIMB_LENGTH_LOSS_WEIGHT: 1
  FTOL: 1e-4
  GLOBAL_ITERS: 3

INIT_SMPL:
  VIS: True
  # VIS: False
  VIS_CAMERAS: ['cam01', 'cam03', 'cam13']
  # VIS_CAMERAS: []

SMPL:
  # VIS_CAMERAS: ['cam01', 'cam02', 'cam08', 'cam14', 'cam19']
  VIS_CAMERAS: []
  # VIS_CAMERAS: ['cam01', 'cam03', 'cam13']
  DEBUG: False
  VERBOSE: True
  CONFIG_FILE: 'smplify3d_temporal.py'
  ARIA_NAME_LIST: ['aria01', 'aria02']
  ARIA_GENDER_LIST: ['neutral', 'neutral']
  NUM_EPOCHS_LIST: [2, 20]
  STAGE1_ITERS_LIST: [50, 50] ## global rot and transl
  STAGE2_ITERS_LIST: [10, 100] ## ## shape optimize
  STAGE3_ITERS_LIST: [10, 150] ## global rot and transl and pose. Use small iterations if crouching problem

BLENDER:
  SCENE_FILE: 'ballroom/ballroom.blend'
  COLORS: 'red###blue'
  MAX_OFFSET: 0.25
  TOLERANCE: 1e-5
  OVERLAY: True
  OVERLAY_CAMERA: 'cam08'
